language: python
python:
  - '3.8'
install:
  - pipenv install --dev
script:
  - pipenv run python -m flake8
  - pipenv run pytest
deploy:
  provider: script
  script: bash deployment/deploy.sh
  on:
    branch: master
  skip_cleanup: true
before_install:
  - openssl aes-256-cbc -K $encrypted_f50f2e55db45_key -iv $encrypted_f50f2e55db45_iv
    -in deployment/deployment.key.enc -out deployment/deployment.key -d
